model_name: hist_gradient_boosting
artifact_path: basic_hgb

tag_key: "model"
tag_value: "basic HGB"

module_name: "sklearn.ensemble"
class_name: "HistGradientBoostingRegressor"

params:
  max_depth: [6, 8, 10]
  loss: ['squared_error', 'absolute_error', 'poisson']
  learning_rate: [0.1, 0.3, 0.5]