model_name: logistic_regression
artifact_path: basic_lr

tag_key: "model"
tag_value: "basic LR"

module_name: "sklearn.linear_model"
class_name: "LogisticRegression"

params:
  solver: ["saga", "lbfgs", "liblinear"]
  max_iter: [100, 200, 1000]
  random_state: [88]
  C: [0.1, 0.5, 0.9]