defaults:
  - _self_

folds: 2

evaluation_metric: "neg_mean_squared_error" # Updated to a regression metric
cv_evaluation_metric: "neg_mean_squared_error"

pyfunc_predict_fn: "predict"

metrics:
  rmse: "neg_mean_squared_error" # Added RMSE as a metric
  r2: "r2"

challenger_model_names: ['neural_network', 'neural_network', 'random_forest', 'random_forest']
rmse_threshold: 20