defaults: # TODO: check correctness of params
  - _self_

folds: 3

evaluation_metric: "neg_mean_absolute_error"
cv_evaluation_metric: "neg_mean_mean_test_f1"

pyfunc_predict_fn: "predict_proba"

metrics:
  mean_absolute_error: "neg_mean_absolute_error"
  mean_squared_error: "neg_mean_squared_error"
  r2: "r2"


# hydra:
#   sweeper:
#       sampler:
#         seed: 8888
#       # n_trials: 20 # number of times to try to optimize the search space
#       direction: maximize # minimize
