model_name: neural_network
artifact_path: basic_nn

tag_key: "model"
tag_value: "basic nn"

module_name: "sklearn.neural_network"
class_name: "MLPRegressor"

params:
  solver: ['lbfgs', 'sgd', 'adam']
  activation: ['logistic', 'tanh', 'relu']
  hidden_layer_sizes: [(100, ), (100, 100), (100, 100, 100)]