model_name: neural_network
artifact_path: basic_nn

tag_key: "model"
tag_value: "basic nn"

module_name: "sklearn.neural_network"
class_name: "MLPRegressor"

params:
  solver: ['adam']
  learning_rate: ["constant", "invscaling", "adaptive"]
  activation: ['logistic', 'tanh', 'relu']
  random_state: [88, 100, 44]