model_name: neural_network # TODO: make our model
artifact_path: basic_nn

tag_key: "model"
tag_value: "basic nn"

module_name: "sklearn.neural_network"
class_name: "MLPRegressor"

params:
  # hidden_layer_sizes: [(100,), (100, 100), (100, 100, 100)]
  solver: ['lbfgs', 'sgd', 'adam']
  learning_rate: ["constant", "invscaling", "adaptive"]
  activation: ['logistic', 'tanh', 'relu']
  random_state: [88, 100, 44]
  max_iter: [100]
  
  # C: [0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9]
  # C: np.arange(0.1, 1, 0.1)

# hydra:
#   sweeper:
#     params:
#       +params.penalty: "'l1', 'l2'"
#       +params.solver: "'saga'"
#       +params.max_iter: "100, 200, 1000"
#       +params.random_state: 88
#       +params.C: range(start=0.1, stop=1, step=0.1)