model_name: support_vector_regression
artifact_path: basic_svr

tag_key: "model"
tag_value: "support vector regression"

module_name: "sklearn.svm"
class_name: "SVR"

params:
  C: [0.1, 1.0, 10]
  epsilon: [0.1, 0.2, 0.5]
  kernel: ['linear', 'poly', 'rbf']