data:
  target_features: ["popularity"]
  genres_features: ["genres"]
  multilabel_features: ["available_markets"]
  categorical_features: ["key", "time_signature"]
  normal_features: ["artist_followers","album_total_tracks","artist_popularity","tempo","speechiness","danceability","liveness","loudness"]
  uniform_features: ["energy","valence","acousticness","instrumentalness"]
  convert_to_bool: ["explicit"]
  ordinal_features: ["chart", "mode"]
  timedate_features: ["album_release_date"]
  low_features_number: ["track_id","streams","track_artists","added_at","track_album_album","duration_ms", "track_track_number", "rank", "region", "trend"]
  text_features: ["album_name", "name"]
  