data:
  num_samples: 5
  path_to_raw: ./data/raw/tracks.csv
  remote: mlops_remote
  repo: .
  sample_num: 16
  version: AIRFLOW2.4
  dataset_name: music_popularity

defaults:
- _self_
- data_features
- model/model
- experiment
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: hgb, nn

mlflow_port: 5000
model_port: 5151
docker_port: 5152
web_ui_port: 5155
transformer_version: v1