data:
  dataset_name: music_popularity
  num_samples: 5
  path_to_raw: ./data/raw/tracks.csv
  remote: mlops_remote
  repo: .
  sample_num: 5
  version: AIRFLOW2.2
defaults:
- _self_
- data_features
- model/model
- experiment
docker_port: 5152
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: hgb, nn
mae_threshold: 12
mlflow_port: 5000
model_port: 5151
rmse_threshold: 15
transformer_version: v1
web_ui_port: 5155
