data:
  num_samples: 5
  path_to_raw: ./data/raw/tracks.csv
  remote: mlops_remote
  repo: .
  sample_num: 16
  version: AIRFLOW2.0
  dataset_name: music_popularity

defaults:
- _self_
- data_features
- model/model
- experiment
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: nn, rf

mlflow_port: 5000
model_port: 5151
transformer_version: v1