data:
  num_samples: 5
  path_to_raw: ./data/raw/tracks.csv
  remote: mlops_remote
  repo: .
  sample_num: 17
  version: AIRFLOW2.0
  dataset_name: music_popularity
defaults:
- _self_
- data_features
- model/model
- experiment
hydra:
  mode: MULTIRUN
  sweeper:
    params:
      +model: rf, nn
